stages:
  - prepare
  - build

before_script:
  - "ln -s $CACHEDIR packer_cache"
  - "git submodule sync --recursive"
  - "git submodule update --init --recursive"

variables:
  TMPDIR: "/datos/gitlab-ci/tmp"
  CACHEDIR: "/datos/gitlab-ci/packer_cache"

prepare_job:
  stage: prepare
  script:
    - "mkdir -p $TMPDIR"
    - "mkdir -p $CACHEDIR"

build_job:
  stage: build
  script:
    - "PACKER=/usr/local/bin/packer make test-virtualbox/fedora24"
  artifacts:
    paths:
      - 'box/virtualbox/*.box'

